---
- name: to install httpd giving handlers
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    notify: start apache

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started    
