---
- name: this playbook is to install and start the httpd service
  hosts: all
  become: true
  tasks: 
  - name: to install httpd
    yum:
     name: httpd
     state: installed

  - name: start service
    service:
      name: httpd
      state: started

