---
- name: sample playbook
  hosts: all
  become: true
  tasks:
  - name: to add multiple users
    user: 
     name: '{{item}}'
     state: present
    with_items: 
     - raj
     - hari
     - sai   
