---
# tasks file for setup-roles
- name: install httpd package
  yum:
    name: "{{httpd_package_name}}"
    state: installed
  notify: start httpd service
  when: ansible_os_family == "RedHat"

- name: install apache2 package
  apt:
    name: "{{apache2_Package_name}}"
    state: present
  notify : start apache2 package
  when: ansible_os_family == "Debian"
